In [2]:
import numpy as np
myarray = np.arange(10)
# 偶数切片
s = slice(0,10,2)  # 返回的是索引
myarray = myarray[s]

array2 = np.arange(20)
array2.shape = (4,5)
print(array2)
array2[1][1:3]
# 取出第二行
array2[1,:]
# 取出第二列
array2[:,1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 1,  6, 11, 16])

In [3]:
# 等差数列
a = np.linspace(0,10,5)
a

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [4]:
a + np.random.random(5)

array([  0.86875988,   3.40104472,   5.17850922,   8.21403799,  10.66408588])