In [6]:
import numpy as np
myarray = np.arange(9)
myarray.shape = (3,3)
myarray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# 取出对角线元素
mydata = myarray[[0,1,2],[0,1,2]] # 00,11,22:xy的坐标
mydata

array([0, 4, 8])

In [8]:
# 反对角线元素
mydata = myarray[[0,1,2],[2,1,0]]
mydata

array([2, 4, 6])