In [1]:
import numpy as np

In [2]:
myarray = np.arange(12)
myarray.shape = (4,3)
myarray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
myarray[myarray < 5]

array([0, 1, 2, 3, 4])

In [4]:
# 取偶
myarray[myarray % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [5]:
# ~ 为取补运算符
a = np.array([np.nan,1,2,np.nan,3,4,5])
# 筛选无效数据
a[~np.isnan(a)]

array([ 1.,  2.,  3.,  4.,  5.])

In [6]:
a = np.array([1,2+6j,5,3.5+5j])
# 只要复数
a[np.iscomplex(a)]

array([ 2.0+6.j,  3.5+5.j])