In [1]:
import numpy as np
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])

In [2]:
# 广播要求形状一致,也就是列数(宽度)要一样
a + b

array([ 3,  7, 11, 15])

In [3]:
a * b

array([ 2, 12, 30, 56])

In [4]:
a = np.array([[1,3,5,7],[10,20,30,40]])
a + b

array([[ 3,  7, 11, 15],
       [12, 24, 36, 48]])