In [8]:
import numpy as np
a = np.arange(12)
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
# 迭代器,np.nditer()
# 遍历每一个元素
for x in np.nditer(a):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [4]:
# 矩阵转置
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [16]:
print(a)
# 遍历每一个元素,与矩阵的shape无关
for x in np.nditer(a.T):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [14]:
# C风格,从左往右,从上往下
# F风格,从上至下,从左往右
c = a.copy(order="C")
for x in np.nditer(c):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [15]:
# 拷贝数组,可以指定顺序
c = a.copy(order="F")
# 只读权限,不能修改
for x in np.nditer(c):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [18]:
for x in np.nditer(a,op_flags=["readwrite"]):  # 读写权限
    # 翻倍
    x[...] = 2 * x
a

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [20]:
# 可广播迭代
# 前提是可广播,即列数相同
b = np.array([1,3,5,7])
for x,y in np.nditer([a,b]):
    print(x,y)

0 1
4 3
8 5
12 7
16 1
20 3
24 5
28 7
32 1
36 3
40 5
44 7
