In [1]:
import numpy as np
a = np.arange(0,100,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [3]:
a = a.reshape(4,5)
a

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [6]:
# 返回数组的副本,折叠成一维
a.flatten(order="F")

array([ 0, 25, 50, 75,  5, 30, 55, 80, 10, 35, 60, 85, 15, 40, 65, 90, 20,
       45, 70, 95])

In [7]:
# 返回一维数组
a.ravel()

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])