In [1]:
import numpy as np
a = np.arange(0,100,5)
a.shape = (4,5)
a

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [2]:
a.T

array([[ 0, 25, 50, 75],
       [ 5, 30, 55, 80],
       [10, 35, 60, 85],
       [15, 40, 65, 90],
       [20, 45, 70, 95]])

In [4]:
# 转置
np.transpose(a)

array([[ 0, 25, 50, 75],
       [ 5, 30, 55, 80],
       [10, 35, 60, 85],
       [15, 40, 65, 90],
       [20, 45, 70, 95]])

In [15]:
b = np.arange(24).reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [16]:
np.rollaxis(b,2,1)

array([[[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]],

       [[12, 15, 18, 21],
        [13, 16, 19, 22],
        [14, 17, 20, 23]]])

In [11]:
a = np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
# 按轴滚动
np.rollaxis(a,2,1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [25]:
# [x][y][z]
# [y][x][z] 0
# [x][z][y] 1
# [z][x][y] 2
# 默认为0,表示完整的滚动
# [y][x][z] 0 0
# [y][x][z] 0,2  
# 第二个参数代表滚动到哪个位置
np.rollaxis(a,2)

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

In [26]:
np.swapaxes(a,2,0)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [23]:
# 轴的交换
b = np.array([1,2,3,4,5,6])
b = b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.swapaxes(b,1,0)

array([[1, 4],
       [2, 5],
       [3, 6]])