In [17]:
import numpy as np
x = np.array([[1], [2], [3]])
# 对y广播x,生成的相当于迭代器
y = np.array([4, 5, 6])
b = np.broadcast(x,y)
print(b.__next__())
# print(b.__next__())
# print(b.__next__())
# print(b.__next__())
# print(b.__next__())
# print(b.__next__())
print(b.index)
print(b.shape)

(1, 4)
1
(3, 3)


In [18]:
# 清空数组
c = np.empty(b.shape)

In [24]:
c.flat = [u+v for (u,v) in b]
c

array([[ 5.,  6.,  7.],
       [ 6.,  7.,  8.],
       [ 7.,  8.,  9.]])

In [3]:
a = np.arange(4).reshape(1,4)
a

array([[0, 1, 2, 3]])

In [26]:
# 映射为四行四列
np.broadcast_to(a,(4,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [29]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [6]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [19]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a = np.array([4,2,7,8])
np.argmax(a)  # 返回最大值的索引

3

In [9]:
# 按列
np.argmax(a,axis=0)

array([1, 1, 1], dtype=int64)

In [10]:
# 按行
np.argmax(a,axis=1)

array([2, 2], dtype=int64)

In [13]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
x = np.array([4,6,2,12,23,8])
# print(x.argsort())
# x[x.argsort()]
x[x[:len(x)-1].argsort()]  # 根据前n项进行排序,不抱括第n项

array([ 2,  4,  6, 12, 23])