In [2]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [4]:
# 拼接,按列拼接
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
# 按行拼接
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [6]:
# 按轴0拼接,按列
# 两个二维变成一个三维
np.stack((a,b),0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
# 按行
np.stack((a,b),1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [8]:
# 水平堆叠,按列
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [9]:
# 垂直堆叠
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])