In [1]:
import numpy as np
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
b = np.resize(a,(3,3))

In [4]:
b.shape

(3, 3)

In [6]:
b = np.resize(a,(3,4))
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 0, 1, 2]])

In [9]:
# 追加
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b = np.append(a,10)
b

array([ 1,  2,  3,  4,  5,  6, 10])

In [11]:
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 沿轴0增加元素
np.append(a,[[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.append(a,[[7,8],[9,10]],axis=1)

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

In [16]:
# 在指定索引处插入值,也不会改变原来数据
np.insert(a,2,[100,101])

array([  1,   2, 100, 101,   3,   4,   5,   6])

In [20]:
# 在指定索引处插入整行
np.insert(a,2,[7,8,9],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.insert(a,2,[[10,11],[5,5]],axis=1)

array([[ 1,  2, 10,  5,  3],
       [ 4,  5, 11,  5,  6]])

In [32]:
a = np.array([[4,5,6],[7,8,9]])
a

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
# 删除指定索引的值,并返回以为列表
np.delete(a,5)

array([4, 5, 6, 7, 8])

In [33]:
# 删除第0行
np.delete(a,0,axis=0)

array([[7, 8, 9]])

In [34]:
a = np.array([5,2,0,0,2,5])

In [35]:
# 去重,返回一维数组
np.unique(a)

array([0, 2, 5])

In [42]:
a = np.array([[1,3],[1,3],[1,3]])
a

array([[1, 3],
       [1, 3],
       [1, 3]])

In [43]:
np.unique(a)

array([1, 3])

In [44]:
a = np.array([[1,3],[1,3],[1,5]])
np.unique(a)

array([1, 3, 5])

In [46]:
u,index = np.unique(a,return_index=True)
# 原数组索引
print(index)

[0 1 5]
