In [1]:
import numpy as np
np.pi

3.141592653589793

In [14]:
# 转角度
np.degrees(np.pi)

180.0

In [18]:
np.sin(3.14)

0.0015926529164868282

In [19]:
# 参数为弧度,角度先转弧度
np.sin(np.radians(90))

1.0

In [28]:
a = np.array([1.0,2.1,5.2,3.6,0.78])
a

array([ 1.  ,  2.1 ,  5.2 ,  3.6 ,  0.78])

In [29]:
np.around(a)
# 保留1位小数
np.around(a,decimals=1)

array([ 1. ,  2.1,  5.2,  3.6,  0.8])

In [30]:
np.floor(a)

array([ 1.,  2.,  5.,  3.,  0.])

In [31]:
np.ceil(a)

array([ 1.,  3.,  6.,  4.,  1.])