In [11]:
import numpy as np
a = np.arange(10)
a

In [9]:
b = np.arange(1,11).reshape(10,1)
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [10]:
a + b 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [12]:
a1  = np.arange(16).reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
b1 = np.array([10,20,30,40])

In [16]:
# 加法
np.add(a1,b1)

array([[10, 21, 32, 43],
       [14, 25, 36, 47],
       [18, 29, 40, 51],
       [22, 33, 44, 55]])

In [17]:
# 减法
np.subtract(a1,b1)

array([[-10, -19, -28, -37],
       [ -6, -15, -24, -33],
       [ -2, -11, -20, -29],
       [  2,  -7, -16, -25]])

In [18]:
# 乘法
np.multiply(a1,b1)

array([[  0,  20,  60, 120],
       [ 40, 100, 180, 280],
       [ 80, 180, 300, 440],
       [120, 260, 420, 600]])

In [19]:
np.divide(a1,b1)

array([[ 0.        ,  0.05      ,  0.06666667,  0.075     ],
       [ 0.4       ,  0.25      ,  0.2       ,  0.175     ],
       [ 0.8       ,  0.45      ,  0.33333333,  0.275     ],
       [ 1.2       ,  0.65      ,  0.46666667,  0.375     ]])